import {
  ArrowUpRight,
  Building2,
  CalendarClock,
  ChartNoAxesColumn,
  CircleUser,
  CornerUpRight,
  DatabaseBackup,
  Download,
  FileText,
  HardHat,
  House,
  Images,
  Inbox,
  LayoutList,
  LifeBuoy,
  ListFilter,
  LogOut,
  MapPin,
  Menu,
  MessageCircleQuestion,
  Newspaper,
  Palette,
  Paperclip,
  PanelBottom,
  Phone,
  Search,
  SendHorizontal,
  SquareSlash,
  Settings,
  Sparkles,
  Star,
  Tags,
  Truck,
  Undo2,
  Users,
  Wrench,
} from 'lucide-react'
import React from 'react'

/** One line-icon set for the whole admin, looked up by name so server code can pass plain strings. */
const icons = {
  account: CircleUser,
  attach: Paperclip,
  ai: Sparkles,
  backup: DatabaseBackup,
  categories: Tags,
  commands: SquareSlash,
  company: Building2,
  download: Download,
  equipment: Truck,
  external: ArrowUpRight,
  faqs: MessageCircleQuestion,
  footer: PanelBottom,
  forms: LayoutList,
  help: LifeBuoy,
  home: House,
  leads: Inbox,
  listings: ListFilter,
  logout: LogOut,
  menu: Menu,
  news: Newspaper,
  pages: FileText,
  palette: Palette,
  phone: Phone,
  photos: Images,
  projects: HardHat,
  redirects: CornerUpRight,
  reviews: Star,
  schedule: CalendarClock,
  search: Search,
  send: SendHorizontal,
  services: Wrench,
  stats: ChartNoAxesColumn,
  settings: Settings,
  towns: MapPin,
  undo: Undo2,
  users: Users,
}

export type IconName = keyof typeof icons

export const Icon: React.FC<{ name: IconName; size?: number }> = ({ name, size = 22 }) => {
  const Cmp = icons[name]
  return <Cmp aria-hidden="true" size={size} strokeWidth={1.75} />
}
