/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'form-submissions': FormSubmission;
    pages: Page;
    projects: Project;
    posts: Post;
    media: Media;
    services: Service;
    equipment: Equipment;
    'service-areas': ServiceArea;
    testimonials: Testimonial;
    faqs: Faq;
    users: User;
    categories: Category;
    redirects: Redirect;
    forms: Form;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    theme: Theme;
    header: Header;
    footer: Footer;
    'listing-pages': ListingPage;
    'backup-settings': BackupSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'listing-pages': ListingPagesSelect<false> | ListingPagesSelect<true>;
    'backup-settings': BackupSettingsSelect<false> | BackupSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Everyone who sent the estimate form. Open one to see the details, then set its status as you follow up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  contactName?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  serviceWanted?: string | null;
  details?: string | null;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Update this as you follow up.
   */
  status?: ('new' | 'contacted' | 'quoted' | 'won' | 'lost') | null;
  notes?: string | null;
  sourcePage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your pages. Open one to change its text and photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Each row is one section of the page, from top to bottom. Click a row to edit it, drag ⠿ to reorder, and use the eye icon (top right) to see the page while you edit.
   */
  layout: (
    | HeroHomeBlock
    | PageHeroBlock
    | ServicesGridBlock
    | FeaturedProjectsBlock
    | SplitBlock
    | CardsBlock
    | StepsBlock
    | StatsBlock
    | MarqueeBlock
    | EquipmentGridBlock
    | ChecklistBlock
    | TestimonialsBlock
    | FAQBlock
    | ServiceAreasBlock
    | GalleryBlock
    | ContactSectionBlock
    | CtaBandBlock
    | ContentBlock
    | MediaBlock
    | FormBlock
    | ArchiveBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  hideCtaBand?: boolean | null;
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomeBlock".
 */
export interface HeroHomeBlock {
  variant?: ('fullImage' | 'split') | null;
  showLogo?: boolean | null;
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading: string;
  lede?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null)
            | ({
                relationTo: 'service-areas';
                value: number | ServiceArea;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  trust?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  thumbs?: (number | Media)[] | null;
  showBadge?: boolean | null;
  showCallCard?: boolean | null;
  callCardText?: string | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroHome';
}
/**
 * News, tips and project updates shown at /posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * All images and files. Photos are resized and converted to WebP automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the photo for screen readers and Google (e.g. "Excavator digging a pool in Lewes"). Filled from the file name if left empty.
   */
  alt?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log in here. Give staff the "Editor" role.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Editor: pages, projects, news, photos and quote requests. Manager: also company info, colours, menu, users and backups. Admin: everything, including technical settings.
   */
  role: 'editor' | 'manager' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The services you offer. Each one gets its own page at /services/<slug>.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  icon?:
    | (
        | 'mulch'
        | 'clear'
        | 'grade'
        | 'demo'
        | 'excav'
        | 'drive'
        | 'pad'
        | 'clean'
        | 'pavers'
        | 'roof'
        | 'arrow'
        | 'arrowUpRight'
        | 'check'
        | 'phone'
        | 'pin'
        | 'area'
        | 'calendar'
        | 'clock'
        | 'shield'
        | 'star'
        | 'users'
        | 'leaf'
        | 'truck'
        | 'hammer'
        | 'award'
        | 'handshake'
        | 'mail'
      )
    | null;
  /**
   * One or two sentences, shown on cards and in the services grid.
   */
  shortDescription: string;
  /**
   * Used as the large photo tile and as the service page hero.
   */
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  faqs?: (number | Faq)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Lower numbers are shown first.
   */
  order?: number | null;
  showInFooter?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your finished jobs. They appear on the Projects page of the website, where visitors can filter them by service, lot size, town and year.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Short scope of work — shown on the card and at the top of the project page.
   */
  summary: string;
  cover: number | Media;
  /**
   * The first service is used as the card badge.
   */
  services: (number | Service)[];
  area: number | ServiceArea;
  clientType?: ('residential' | 'commercial' | 'municipal' | 'agricultural') | null;
  lotSize: number;
  lotUnit: 'acres' | 'sqft';
  /**
   * Calculated on save — used by the lot-size filter.
   */
  acres?: number | null;
  completedAt: string;
  /**
   * Auto, from completion date.
   */
  year?: number | null;
  duration?: string | null;
  /**
   * Show in "Featured projects" sections set to featured mode.
   */
  featured?: boolean | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Use two photos taken from the same spot.
   */
  beforeAfter?: {
    before?: (number | null) | Media;
    after?: (number | null) | Media;
  };
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  equipment?: (number | Equipment)[] | null;
  /**
   * Free-text tags, e.g. "Roofing crew".
   */
  extraEquipment?: string[] | null;
  testimonial?: (number | null) | Testimonial;
  /**
   * Optional, e.g. "Off Route 9". Avoid exact client addresses.
   */
  locationNote?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Towns you work in. Used by the project filter and local landing pages (/areas/<slug>).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  name: string;
  county?: string | null;
  state?: string | null;
  /**
   * Shown on the town page. A few sentences about the work you do there.
   */
  description?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  order?: number | null;
  hasPage?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Machines in your fleet, shown on the Capabilities page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: number;
  name: string;
  category: 'excavator' | 'mulcher' | 'loader' | 'dozer' | 'wheel-loader' | 'truck' | 'tools' | 'other';
  icon?:
    ('fleetExcavator' | 'fleetMulcher' | 'fleetSkid' | 'fleetDozer' | 'fleetWheelLoader' | 'fleetDumpTruck') | null;
  spec?: string | null;
  description?: string | null;
  /**
   * If set, the photo replaces the drawn icon.
   */
  image?: (number | null) | Media;
  brand?: string | null;
  model?: string | null;
  quantity?: number | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers are shown first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  location?: string | null;
  rating: number;
  quote: string;
  source?: ('direct' | 'google' | 'facebook' | 'angi' | 'yelp') | null;
  date?: string | null;
  /**
   * Optional — links the review to a finished job.
   */
  project?: (number | null) | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock".
 */
export interface PageHeroBlock {
  variant?: ('split' | 'simple' | 'image') | null;
  showBreadcrumbs?: boolean | null;
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading: string;
  lede?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null)
            | ({
                relationTo: 'service-areas';
                value: number | ServiceArea;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock".
 */
export interface ServicesGridBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  headerLink?: {
    label?: string | null;
    /**
     * e.g. /projects or /contact
     */
    url?: string | null;
  };
  variant?: ('bento' | 'cards' | 'list') | null;
  source?: ('all' | 'manual') | null;
  services?: (number | Service)[] | null;
  /**
   * These use the service photo. Up to 3.
   */
  photoTiles?: (number | Service)[] | null;
  linkTo?: ('service' | 'projects') | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProjectsBlock".
 */
export interface FeaturedProjectsBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  headerLink?: {
    label?: string | null;
    /**
     * e.g. /projects or /contact
     */
    url?: string | null;
  };
  source?: ('latest' | 'featured' | 'manual') | null;
  limit?: number | null;
  layout?: ('feature' | 'grid') | null;
  projects?: (number | Project)[] | null;
  filterService?: (number | null) | Service;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredProjects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitBlock".
 */
export interface SplitBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null)
            | ({
                relationTo: 'service-areas';
                value: number | ServiceArea;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  imagePosition?: ('right' | 'left') | null;
  stamp?: {
    title?: string | null;
    text?: string | null;
  };
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'split';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock".
 */
export interface CardsBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  headerLink?: {
    label?: string | null;
    /**
     * e.g. /projects or /contact
     */
    url?: string | null;
  };
  variant?: ('value' | 'icon' | 'row') | null;
  columns?: ('2' | '3' | '4') | null;
  items: {
    title: string;
    icon?:
      | (
          | 'mulch'
          | 'clear'
          | 'grade'
          | 'demo'
          | 'excav'
          | 'drive'
          | 'pad'
          | 'clean'
          | 'pavers'
          | 'roof'
          | 'arrow'
          | 'arrowUpRight'
          | 'check'
          | 'phone'
          | 'pin'
          | 'area'
          | 'calendar'
          | 'clock'
          | 'shield'
          | 'star'
          | 'users'
          | 'leaf'
          | 'truck'
          | 'hammer'
          | 'award'
          | 'handshake'
          | 'mail'
          | 'techGps'
          | 'techDrone'
          | 'techLaser'
          | 'techDoc'
        )
      | null;
    text?: string | null;
    id?: string | null;
  }[];
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  steps: {
    title: string;
    text?: string | null;
    id?: string | null;
  }[];
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  items: {
    value: string;
    label: string;
    id?: string | null;
  }[];
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock".
 */
export interface MarqueeBlock {
  source?: ('services' | 'custom') | null;
  items?: string[] | null;
  style?: ('brand' | 'dark' | 'outline') | null;
  speed?: ('slow' | 'normal' | 'fast') | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EquipmentGridBlock".
 */
export interface EquipmentGridBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  /**
   * Leave empty to show all equipment.
   */
  categories?: ('excavator' | 'mulcher' | 'loader' | 'dozer' | 'wheel-loader' | 'truck' | 'tools' | 'other')[] | null;
  showFilter?: boolean | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'equipmentGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock".
 */
export interface ChecklistBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  items: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'checklist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  source?: ('latest' | 'manual') | null;
  limit?: number | null;
  items?: (number | Testimonial)[] | null;
  showRating?: boolean | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  /**
   * Leave empty to show all FAQs.
   */
  items?: (number | Faq)[] | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceAreasBlock".
 */
export interface ServiceAreasBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  linkToPages?: boolean | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'serviceAreas';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  images: (number | Media)[];
  columns?: ('2' | '3' | '4') | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock".
 */
export interface ContactSectionBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading?: string | null;
  lede?: string | null;
  /**
   * Build or edit forms under Forms in the sidebar.
   */
  form: number | Form;
  showInfoCard?: boolean | null;
  showMap?: boolean | null;
  footnote?: string | null;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock".
 */
export interface CtaBandBlock {
  /**
   * Optional short label, e.g. "Our services".
   */
  eyebrow?: string | null;
  /**
   * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
   */
  heading: string;
  lede?: string | null;
  showPhone?: boolean | null;
  buttonLabel?: string | null;
  buttonUrl?: string | null;
  style?: ('gradient' | 'dark' | 'image') | null;
  image?: (number | null) | Media;
  /**
   * Background, spacing and visibility of this section.
   */
  settings?: {
    background?: ('default' | 'alt' | 'tint' | 'dark') | null;
    spacing?: ('none' | 'sm' | 'md' | 'lg') | null;
    hideOn?: ('none' | 'mobile' | 'desktop' | 'all') | null;
    /**
     * Optional. Lets menus link straight to this section, e.g. "services" → /#services.
     */
    anchor?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null)
            | ({
                relationTo: 'service-areas';
                value: number | ServiceArea;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Old path, e.g. /old-page. Visitors are sent to the new destination.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'posts';
        value: number | Post;
      }
    | {
        relationTo: 'projects';
        value: number | Project;
      }
    | {
        relationTo: 'services';
        value: number | Service;
      }
    | {
        relationTo: 'pages';
        value: number | Page;
      };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'equipment';
        value: number | Equipment;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  serviceWanted?: T;
  details?: T;
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  status?: T;
  notes?: T;
  sourcePage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        heroHome?: T | HeroHomeBlockSelect<T>;
        pageHero?: T | PageHeroBlockSelect<T>;
        servicesGrid?: T | ServicesGridBlockSelect<T>;
        featuredProjects?: T | FeaturedProjectsBlockSelect<T>;
        split?: T | SplitBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        marquee?: T | MarqueeBlockSelect<T>;
        equipmentGrid?: T | EquipmentGridBlockSelect<T>;
        checklist?: T | ChecklistBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        serviceAreas?: T | ServiceAreasBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        contactSection?: T | ContactSectionBlockSelect<T>;
        ctaBand?: T | CtaBandBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  hideCtaBand?: T;
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomeBlock_select".
 */
export interface HeroHomeBlockSelect<T extends boolean = true> {
  variant?: T;
  showLogo?: T;
  eyebrow?: T;
  heading?: T;
  lede?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  trust?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  image?: T;
  thumbs?: T;
  showBadge?: T;
  showCallCard?: T;
  callCardText?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock_select".
 */
export interface PageHeroBlockSelect<T extends boolean = true> {
  variant?: T;
  showBreadcrumbs?: T;
  eyebrow?: T;
  heading?: T;
  lede?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  image?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesGridBlock_select".
 */
export interface ServicesGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  headerLink?:
    | T
    | {
        label?: T;
        url?: T;
      };
  variant?: T;
  source?: T;
  services?: T;
  photoTiles?: T;
  linkTo?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProjectsBlock_select".
 */
export interface FeaturedProjectsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  headerLink?:
    | T
    | {
        label?: T;
        url?: T;
      };
  source?: T;
  limit?: T;
  layout?: T;
  projects?: T;
  filterService?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitBlock_select".
 */
export interface SplitBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  body?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  image?: T;
  imagePosition?: T;
  stamp?:
    | T
    | {
        title?: T;
        text?: T;
      };
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock_select".
 */
export interface CardsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  headerLink?:
    | T
    | {
        label?: T;
        url?: T;
      };
  variant?: T;
  columns?: T;
  items?:
    | T
    | {
        title?: T;
        icon?: T;
        text?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  steps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock_select".
 */
export interface MarqueeBlockSelect<T extends boolean = true> {
  source?: T;
  items?: T;
  style?: T;
  speed?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EquipmentGridBlock_select".
 */
export interface EquipmentGridBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  categories?: T;
  showFilter?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock_select".
 */
export interface ChecklistBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  source?: T;
  limit?: T;
  items?: T;
  showRating?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  items?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceAreasBlock_select".
 */
export interface ServiceAreasBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  linkToPages?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  images?: T;
  columns?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock_select".
 */
export interface ContactSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  form?: T;
  showInfoCard?: T;
  showMap?: T;
  footnote?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock_select".
 */
export interface CtaBandBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lede?: T;
  showPhone?: T;
  buttonLabel?: T;
  buttonUrl?: T;
  style?: T;
  image?: T;
  settings?:
    | T
    | {
        background?: T;
        spacing?: T;
        hideOn?: T;
        anchor?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  cover?: T;
  services?: T;
  area?: T;
  clientType?: T;
  lotSize?: T;
  lotUnit?: T;
  acres?: T;
  completedAt?: T;
  year?: T;
  duration?: T;
  featured?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
      };
  body?: T;
  equipment?: T;
  extraEquipment?: T;
  testimonial?: T;
  locationNote?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  icon?: T;
  shortDescription?: T;
  image?: T;
  body?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  order?: T;
  showInFooter?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  icon?: T;
  spec?: T;
  description?: T;
  image?: T;
  brand?: T;
  model?: T;
  quantity?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  name?: T;
  county?: T;
  state?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  order?: T;
  hasPage?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  location?: T;
  rating?: T;
  quote?: T;
  source?: T;
  date?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Company details, logos and site-wide options. Changes appear on the live site right after saving.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  /**
   * Used in page titles, e.g. "Mendez Brothers".
   */
  shortName?: string | null;
  tagline?: string | null;
  /**
   * Shown in the footer and used as the default SEO description.
   */
  description?: string | null;
  phone?: string | null;
  /**
   * Leave empty to use the main phone.
   */
  smsPhone?: string | null;
  email?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    /**
     * Optional. Built from the address if left empty.
     */
    mapUrl?: string | null;
  };
  hours?: string | null;
  serviceAreaText?: string | null;
  /**
   * Optional, e.g. "Licensed & insured · DE Lic. #12345".
   */
  licenseNumber?: string | null;
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'tiktok' | 'linkedin' | 'x' | 'google' | 'yelp';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wordmark used in the header. Transparent PNG, WebP or SVG.
   */
  logo?: (number | null) | Media;
  logoOnDark?: (number | null) | Media;
  /**
   * Round emblem used as a badge on the home hero and as the app icon.
   */
  logoMark?: (number | null) | Media;
  /**
   * Square image, at least 256×256.
   */
  favicon?: (number | null) | Media;
  logoHeight?: number | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  /**
   * Shown on every page except where a page turns it off.
   */
  ctaBand?: {
    enabled?: boolean | null;
    heading?: string | null;
    showPhone?: boolean | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
  };
  mobileCallBar?: boolean | null;
  backToTop?: boolean | null;
  /**
   * Added after every page title, e.g. " | Mendez Brothers".
   */
  titleSuffix?: string | null;
  /**
   * 1200×630 recommended.
   */
  defaultOgImage?: (number | null) | Media;
  businessType?: ('GeneralContractor' | 'HomeAndConstructionBusiness' | 'RoofingContractor' | 'LocalBusiness') | null;
  /**
   * Plausible analytics domain (cookie-free). Optional.
   */
  plausibleDomain?: string | null;
  gaId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 1) Pick a palette (or build one from your brand colour). 2) Open Live Preview to see it on the real site. 3) Publish. Nothing changes for visitors until you publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  preset: 'classic' | 'limestone' | 'graphite' | 'steel' | 'forest' | 'amber' | 'auto';
  /**
   * The one colour everything else is built from (your logo colour).
   */
  brandColor?: string | null;
  neutralTone?: ('warm' | 'neutral' | 'cool') | null;
  autoMode?: ('light' | 'dark') | null;
  colors?: {
    /**
     * Buttons, links, highlights.
     */
    primary?: string | null;
    /**
     * Buttons when hovered.
     */
    primaryHover?: string | null;
    /**
     * End of the brand gradient, tag text.
     */
    primaryDeep?: string | null;
    /**
     * Bright highlight (focus rings, small accents).
     */
    accent?: string | null;
    /**
     * Titles on light backgrounds.
     */
    heading?: string | null;
    text?: string | null;
    /**
     * Intros, captions, meta.
     */
    muted?: string | null;
    background?: string | null;
    /**
     * Light grey sections, inner page heroes.
     */
    alt?: string | null;
    /**
     * Soft brand-coloured sections and tags.
     */
    tint?: string | null;
    /**
     * Card and form background.
     */
    surface?: string | null;
    line?: string | null;
    /**
     * Background of dark bands and dark footer.
     */
    dark?: string | null;
    onDark?: string | null;
  };
  fontDisplay?:
    | (
        | 'preset'
        | 'russo'
        | 'montserrat'
        | 'inter'
        | 'oswald'
        | 'barlowCondensed'
        | 'barlow'
        | 'archivo'
        | 'playfair'
        | 'dmSans'
      )
    | null;
  fontBody?:
    | (
        | 'preset'
        | 'russo'
        | 'montserrat'
        | 'inter'
        | 'oswald'
        | 'barlowCondensed'
        | 'barlow'
        | 'archivo'
        | 'playfair'
        | 'dmSans'
      )
    | null;
  headingCase?: ('preset' | 'uppercase' | 'none') | null;
  baseFontSize?: number | null;
  radius?: ('preset' | 'sharp' | 'soft' | 'rounded') | null;
  buttonShape?: ('preset' | 'square' | 'rounded' | 'pill') | null;
  cardStyle?: ('preset' | 'bordered' | 'shadow' | 'flat') | null;
  container?: ('preset' | 'narrow' | 'default' | 'wide') | null;
  headerStyle?: ('preset' | 'light' | 'dark' | 'brand') | null;
  footerStyle?: ('preset' | 'light' | 'dark') | null;
  stickyHeader?: boolean | null;
  /**
   * Text must contrast 4.5:1 with its background. Both automatic modes guarantee that; they differ only in how buttons look.
   */
  contrastMode?: ('deepen' | 'vivid' | 'off') | null;
  animations?: boolean | null;
  /**
   * Optional. Added at the end of the site stylesheet. For developers.
   */
  customCss?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null)
            | ({
                relationTo: 'service-areas';
                value: number | ServiceArea;
              } | null);
          url?: string | null;
          label: string;
        };
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null)
                  | ({
                      relationTo: 'projects';
                      value: number | Project;
                    } | null)
                  | ({
                      relationTo: 'service-areas';
                      value: number | ServiceArea;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showPhone?: boolean | null;
  /**
   * Optional, e.g. "Free estimate".
   */
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        navItems?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null)
                  | ({
                      relationTo: 'projects';
                      value: number | Project;
                    } | null)
                  | ({
                      relationTo: 'service-areas';
                      value: number | ServiceArea;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showServices?: boolean | null;
  servicesTitle?: string | null;
  showContact?: boolean | null;
  /**
   * e.g. "Lewes, Delaware". The copyright line is generated automatically.
   */
  bottomText?: string | null;
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null)
            | ({
                relationTo: 'service-areas';
                value: number | ServiceArea;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Headings and options for the automatic pages: /projects, /services and /posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages".
 */
export interface ListingPage {
  id: number;
  projects?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
     */
    heading?: string | null;
    lede?: string | null;
    image?: (number | null) | Media;
    perPage?: number | null;
    filters?: ('q' | 'service' | 'area' | 'size' | 'year' | 'type' | 'sort')[] | null;
    /**
     * Leave "max" empty for the last open-ended range. 1 acre = 43,560 sq ft.
     */
    sizeBuckets?:
      | {
          label: string;
          min?: number | null;
          max?: number | null;
          id?: string | null;
        }[]
      | null;
    detailCtaLabel?: string | null;
  };
  services?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
     */
    heading?: string | null;
    lede?: string | null;
    image?: (number | null) | Media;
  };
  posts?: {
    eyebrow?: string | null;
    /**
     * Wrap words in *asterisks* to show them in the brand colour, e.g. "Who *we are*".
     */
    heading?: string | null;
    lede?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Automatic backups are stored on the server. Create, download and restore backups on the Backups screen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-settings".
 */
export interface BackupSetting {
  id: number;
  autoEnabled?: boolean | null;
  frequency?: ('daily' | 'weekly') | null;
  /**
   * Older automatic backups are deleted. Manual backups are kept until you delete them.
   */
  keep?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  shortName?: T;
  tagline?: T;
  description?: T;
  phone?: T;
  smsPhone?: T;
  email?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
        mapUrl?: T;
      };
  hours?: T;
  serviceAreaText?: T;
  licenseNumber?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  logoOnDark?: T;
  logoMark?: T;
  favicon?: T;
  logoHeight?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  ctaBand?:
    | T
    | {
        enabled?: T;
        heading?: T;
        showPhone?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  mobileCallBar?: T;
  backToTop?: T;
  titleSuffix?: T;
  defaultOgImage?: T;
  businessType?: T;
  plausibleDomain?: T;
  gaId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  preset?: T;
  brandColor?: T;
  neutralTone?: T;
  autoMode?: T;
  colors?:
    | T
    | {
        primary?: T;
        primaryHover?: T;
        primaryDeep?: T;
        accent?: T;
        heading?: T;
        text?: T;
        muted?: T;
        background?: T;
        alt?: T;
        tint?: T;
        surface?: T;
        line?: T;
        dark?: T;
        onDark?: T;
      };
  fontDisplay?: T;
  fontBody?: T;
  headingCase?: T;
  baseFontSize?: T;
  radius?: T;
  buttonShape?: T;
  cardStyle?: T;
  container?: T;
  headerStyle?: T;
  footerStyle?: T;
  stickyHeader?: T;
  contrastMode?: T;
  animations?: T;
  customCss?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  showPhone?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        navItems?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  showServices?: T;
  servicesTitle?: T;
  showContact?: T;
  bottomText?: T;
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages_select".
 */
export interface ListingPagesSelect<T extends boolean = true> {
  projects?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
        image?: T;
        perPage?: T;
        filters?: T;
        sizeBuckets?:
          | T
          | {
              label?: T;
              min?: T;
              max?: T;
              id?: T;
            };
        detailCtaLabel?: T;
      };
  services?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
        image?: T;
      };
  posts?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backup-settings_select".
 */
export interface BackupSettingsSelect<T extends boolean = true> {
  autoEnabled?: T;
  frequency?: T;
  keep?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}